In [1]:
import numpy as np
import pandas as pd

# 출력을 소수점 이하 3자리로 제한
%precision 3
# DataFrame의 출력을 소수점 이하 3자리로 제한
pd.set_option('precision',3)

## 변수 초기화

In [2]:
df = pd.read_csv('python_stat_sample-master/data/ch2_scores_em.csv',index_col = 'student number')

# df의 처음 5행을 표시
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [3]:
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [8]:
scores_df = pd.DataFrame({'scores':scores},index = pd.Index(['A','B','C','D','E','F','G','H','I','J'], name = 'student'))
scores_df

scores
student        
A            42
B            69
C            56
D            41
E            57
F            48
G            65
H            49
I            65
J            58

## 중앙값
데이터를 크기 순서대로 나열할 때 정확하게 중앙에 위치한 값

- 중앙값은 평균값에 비해 이상값에 강하다(크게 튀는 값이 있으면 평균값은 대표값이 될 수 없음)
- 데이터의 개수 n이 홀수라면 (n+1)/2번째 데이터가 중앙값
- 데이터의 개수 n이 짝수라면 n/2번째와 n/2+1번째 데이터의 평균이 중앙값

In [9]:
# 순서대로 나열
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [10]:
np.median(scores)

56.5

In [12]:
scores_df.median()

scores    56.5
dtype: float64

## 최빈값
데이터에서 가장 많이 나타나는 값
질적 데이터의 대푯값을 구할 때 사용되는 지표

* 도수분포표를 도입하면 양적 데이터에서도 최빈값을 자연스럽게 정의할 수 있다

In [14]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

# 데이터의 산포도 지표

## 분산과 표준편차

### 편차(Deviation)
편차는 각 데이터가 평균으로 부터 얼마나 떨어져 있는가를 나타내는 지표이다

In [19]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])